baseurl = "https://goodandlost.com/"
languageCode = "en-us"
title = "Good and Lost"
theme = "worldly"
disableLiveReload = true

copyright = "Copyright Kevin Sweet"

[author]
  name = "Kevin Sweet"

# differences in production
uglyUrls = true

[permalinks]
  post = ":filename"
